### ISSUE TITLE
[Release 1.0] Project_id or Project_guid

### ISSUE THREAD

**Issue by bat79a** [BuildingSMART/BCF-API#129]
All id name is called guid but the project have a field project_id or it's a guid.

So I think that his field name must be project_guid ? or guid ?

**Comment by GeorgDangl** [comment]
In practice, I think all servers do use guids, but the BCF XML 2.0 specification did only specify it as a string. Since BCF API 1.0 is based on BCF XML 2.0, the project_id MIGHT not be a guid.
See [the BCF XML 2.0 schema](https://github.com/BuildingSMART/BCF-XML/blob/release_2_0/Schemas/project.xsd#L12-L17).

**Comment by bat79a** [comment]
Thx for your answer.

But if I look at your example, I can see that : 
```
Example Response

[{
    "project_id": "F445F4F2-4D02-4B2A-B612-5E456BEF9137",
	"name": "Example project 1"
},
{
    "project_id": "A233FBB2-3A3B-EFF4-C123-DE22ABC8414",
	"name": "Example project 2"
}]
```

project_id seem's to be a guid not ?

**Comment by GeorgDangl** [comment]
They usually are guids=)
