### ISSUE TITLE
[Release 1.0] Extensions talk about comments but ?

### ISSUE THREAD

**Issue by bat79a** [BuildingSMART/BCF-API#130]
Project extensions documentation said that a comment can be impacted by project extension : 
Project extensions are used to define possible values that can be used in topics and comments

But there is nothing in extensions that impact the topic model ?
The doc is not up to date ?

**Comment by GeorgDangl** [comment]
Extensions (they're called extensions, since in BCF XML it's an user-defined XSD that *extends* the original schema by adding restrictions to certain elements) apply for topics and comments with the following properties:

**topics**
`topic_type`, `topic_status`, `priority`, `labels`, `creation_author`, `modified_author`, `assigned_to` and `bim_snippet.snippet_type` 

**comments**
`status`, `author` and `modified_author`

**Comment by bat79a** [comment]
The text give me that : 
```
Parameters

JSON encoded body using the "application/json" content type.

topic_type	string array	Enumeration of allowed values
topic_status	string array	Enumeration of allowed values
topic_label	string array	Enumeration of allowed values
snippet_type	string array	Enumeration of allowed values
priority	string array	Enumeration of allowed values
user_id_type	string array	Enumeration of allowed values
```

So the topic_status will impact topic_status and comment.status ?
and user_id_type will impact topic.creation_author, topic.modified_author, topic.assigned_to AND comment.author, comment.modified_author ?

Or it's may be just an example an project extension can have other attributes that will impact all the fileds that you give to me ?
Like extension.comment_status will impact comment.status, extension.comment_user_id_type will impact comment.author and comment.modified_author ?

**Comment by GeorgDangl** [comment]
`user_id_type` is a list of project user *emails*. It's part of the extensions to give clients clues who they're working with. So that, for example, when you're creating an issue in your local client you can get a nice dropdown of persons to assign the issue to. From that, whenever users are referenced in an object, they're usually defined in that project's extensions.

As for the other values, the list you cited is exhaustive. No other values are defined by the schema for the project extensions. Some values may be re used. For example, the extensions `topic_status` may be both applied a a `topic.status` element as well as a `comment.status` element.

**Comment by bat79a** [comment]
Okay perfect, so the field name topic_status is not perfect i think
may be status could be a better name... ;p
