### ISSUE TITLE
PUT for project extensions?

### ISSUE THREAD

**Issue by stardotbmp** [BuildingSMART/BCF-API#145]
Is it assumed that all amendments to project extensions are made directly in a server UI rather than interfaced via REST? With many many registers of project users for instance, harmonising these would be extremely useful. a BCF server is unlikely to be the source of truth here.

**Comment by GeorgDangl** [comment]
It's similar to how we dropped the PATCH methods in the latest version - we've encountered quite a few difficulties with this feature so it was deliberately left out of the API, but [it's still there in APIs supporting version 1.0](https://github.com/BuildingSMART/BCF-API/tree/v1.0#416-post-project-extension-services).

In the BCF group, we did actually have the impression that the BCF server itself should be the single source of truth for project settings, that's why we said to set up or edit these settings the servers native UI should be used.

Are you having workloads where you mix multiple BCF servers?

**Comment by stardotbmp** [comment]
Specific use case being the users. 

Given that this project extension provides the list of users' emails that can be used for comments, creation, change register etc. – keeping this aligned with individual contributors or staff within those agencies seems an overhead I'd like to not be part of a BCF server.

**Comment by GeorgDangl** [comment]
We've just discussed this in todays telecon.
The reasoning behind removing the `PUT` for project extensions is that most (all that we know of actually) BCF Servers are integrated into a larger product with it's own user / authentication handling. This doesn't always fit in with the way project extensions are updated, so it's a read-only `GET` resource.

This means that there's a little overhead in creating a "BCF Only Server" to handle user management, but for most server there has to be custom logic for user handling anyways.
