### ISSUE TITLE
Viewpoint should have info about user and timestamp

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-API#163]
Currently in BCF 2.1, there is no way to know which user created a viewpoint, and when it was created. You can assume it is the same time that it was linked to a comment, but that is just an assumption. The fields "created_by" and "created_time" should be added to viewpoint_GET schema.

**Comment by GeorgDangl** [comment]
Hi @jasollien, thanks for the input! We just discussed it in todays BCF call and agree with you, we should introduce a `created_by` and `created_time` property on viewpoints. The properties should be named to be in sync with existing properties.

Additionally, @KevLoh from DDS mentioned that we should also include viewpoint creation in the events. We only need a created event, since per the specification, viewpoints should be immutable.

**Comment by jasollien** [comment]
Great :)

**Comment by GeorgDangl** [comment]
Tracked in #181
