### ISSUE TITLE
Topics should have a version token

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-API#17]
How to reproduce:

Actor 1:
Create a topic
Create a comment with status "error".

Actor 2:
Get comment

Actor 1; Create a new comment with status "warning"

Actor 2: 
Create a new comment, without the intention of changing the status, therefore let it remain "error"

Expected:
Actor 2 should get an 409 Conflict (or similar) error code.

What will happen:
Comment is created and status will be changed back to "error", which is not intentional

How to solve this.
A topic should have a version or state token, which is updated each time it has been changed (for example when status or type is changed). This token should be exposed together with the topic object, and be passed in to the server when editing the topic (for example when creating comments etc...)

For example:

topic: {
   token: 235672659345735;
   ....
}

**Comment by jasollien** [comment]
This might also be relevant for other resources

**Comment by GeorgDangl** [comment]
I think race conditions in changing resources should be handled by the ETag as described in [Section 1.2](https://github.com/BuildingSMART/BCF-API#12-caching).
This would leave such operations stateless and pass the responsibility to the client.

For the comment in particular, I think we've now agreed to drop it completely from the comment resource, so that whenever a change of status is needed it is handled via an update to the topic.
