### ISSUE TITLE
Proposal: Support translucent color

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-API#290]
Currently there is no way to make an element translucent, while still keeping the original color.

I suggest that we all agree on a color value that should be treated translucent, example "000000", or similar.

Also, it should be possible to transluce (or color) all elements except some.

**Comment by GeorgDangl** [comment]
Just a thought, I think right now we can either have three blocks for red, blue, green or four blocks to include transparency. What if just a single block would indicate just a transparency value?

But we should maybe look around a bit more, how such data is expressed in other systems - maybe there's a clever solution that we just don't know😀

**Comment by GeorgDangl** [comment]
From the docs: 
![image](https://user-images.githubusercontent.com/10274404/232446556-aca89854-8c80-4bb0-a27e-ae929d33e534.png)


![image](https://user-images.githubusercontent.com/10274404/232446516-eef72166-2350-4ad8-be5a-9d85bd4d4c0e.png)

So, we can provide transparency IF we also provide colors, but we can't just add a transparency without also specifying the color.

**Comment by ykulbak** [comment]
I propose that transparency should be defined directly under the `compomenets` because it willl be used in a similar fashion to visibility. Clash detection tools, for example, will colour the clashing objects and would apply transparency or a wireframe view to the surrounding objects to retain context (see image).
I propose we create a `transparency` object which would follow the same pattern as `visibility`. It would have a `default_transparency` directive and a set of exceptions to support making "everything transparent" and then highlight a small number of objects.
Transparency will be subject to visibility - a hidden/invisible object will not become visible by having a transparency assignment.

![image](https://user-images.githubusercontent.com/215043/233892225-db240c81-4b71-4c80-a778-d1be217b1c07.png)

**Comment by pasi-paasiala** [comment]
@ykulbak I like this idea. This way we wouldn't need to specify the transparency for each component. It'd be just a rendering hint how to show rest of the model.

**Comment by GeorgDangl** [comment]
We've discussed it in the call, we'll go with that approach😀

**Comment by GeorgDangl** [comment]
We just discussed it in a larger group in the call. The linked PR in the BCF XML repo looks good, and we'll do it that way😀

**Comment by GeorgDangl** [comment]
Closed with #326
