### ISSUE TITLE
Document services

### ISSUE THREAD

**Issue by satoshinishimura-fc** [buildingSMART/BCF-API#301]
This is a question.

I am wondering which apis should be used when implementing document services with [Document services in BCF API](https://github.com/buildingSMART/BCF-API/tree/v2.1#48-document-services) or [Documents API](https://github.com/buildingSMART/documents-API). It seems Documents API provides more detailed services including versions of the document. On the other hand, it does not have the APIs related to a specific project. For instance, BCF API has GET Documents Service that specifies a project by id. 

I appreciate it if anyone teach me the usage of these different APIs with some example usecases. Thank you for your cooperation.

**Comment by GeorgDangl** [comment]
Hey @satoshinishimura-fc, that's a great question😀

The _Documents API_ itself is still being developed, with a release to be expected in a few months. It's intended to let clients and servers (CDEs) exchange documents, and due to its interactivity, it allows you to fully use all CDE features that you need. It is also the only API that allows you to _upload_ documents with metadata, which is the main differentiating factor to the BCF API.

In the _Document Services_ within BCF, it's mostly about giving you means to download files attached to a BCF topic. It's also possible to upload new documents here, but that's optional, and I think it's not widely supported by BCF servers.

**Comment by GeorgDangl** [comment]
Yeah, exactly. In the Documents API, the CDE will present its own API and let the user enter the required data. I think most CDEs will probably have some project in which the document is uploaded to.
