### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by Kanhoto** [buildingSMART/BCF-API#308]
Hello,

I'm working on an Unity project and I don't really understand how am I supposed to use this API ?
I've looked up on internet and still didn't figure out how to make it work.

ps : I'm trying to use it but dunno if it is what I'm looking for.
I'm trying to make a unity plugin to create BCF files from unity

**Comment by GeorgDangl** [comment]
Hey @Kanhoto, thanks for raising the issue!

This repository itself only describes the _API specification_, meaning it's meant as a technical guidance for developers to either implement an API client in their app or API endpoints in their servers. The reason is to have a consistent API that works the same way across different software applications.

In your case, you probably have to build an API client to connect to some BCF server. So, first of all, you need to find a server with which you can connect😀 A lot of collaboration tools now have BCF API capabilities.
