### ISSUE TITLE
Breaking changes in non-versioned parts of the API

### ISSUE THREAD

**Issue by nicktindall** [BuildingSMART/BCF-API#90]
If a server were to support v1 and v2.1 clients, there are some problems with some of the unversioned endpoints

# The version endpoint

In the 2.1 spec it returns an array of versions
https://github.com/BuildingSMART/BCF-API#31-version-service

In the 2.0 spec, it returns a single version
https://github.com/BuildingSMART/BCF-API/tree/v1.0#31-information-services

Because this part of the API is not versioned, a 2.1 server would break a 1.0 client, and vice versa.

# The auth info endpoint

Similar problems exists for the auth info endpoint

2.1 adds a mandatory "http_basic_supported" field, which is not present in 1.0, so a 1.0 server would break a 2.1 client expecting the mandatory field.

Also the dymanic_client_reg_url became mandatory in 2.1 where it was optional in 1.0, so a 1.0 implementation with no dynamic_client_reg_url would break a 2.1 client

https://github.com/BuildingSMART/BCF-API#321-obtaining-authentication-information

https://github.com/BuildingSMART/BCF-API/tree/v1.0#321-obtaining-authentication-information

I'm not sure what the answer is, maybe just implementing clients that can tolerate either, it's just something we noticed when implementing.

**Comment by GeorgDangl** [comment]
The first issue (version endpoint) is fixed in #106. API v1.0 will use the `bcf/version` endpoint while v2.1 and newer will use the `bcf/versions` (plural) endpoint.

Regarding the second issue: In 2.1, we've added [section 1.9](https://github.com/BuildingSMART/BCF-API#19-additional-response-object-properties) to the specification which states that clients should ignore additional, unknown properties, so this should no longer be a problem in the future.
Implementations only supporting 1.0 might not be aware of this, but I think that the impact will be very low. The frameworks and libraries I'm familiar with do already ignore additional properties and I'd think that's true for most implementations dealing with JSON.

**Comment by GeorgDangl** [comment]
#124  now additionally versions the `bcf/{version}/auth` resource
