### ISSUE TITLE
Could we change bitmap type to be a descriptive enum

### ISSUE THREAD

**Issue by nicktindall** [BuildingSMART/BCF-API#93]
The bitmap_type property of the bitmap in BCF 1.0 and 2.1 are an enumeration of 0,1 or 2 which map to PNG, JPG and BMP respectively. (see https://github.com/BuildingSMART/BCF-API/blob/master/Schemas_draft-03/Collaboration/Viewpoint/bitmap.json)

In the BCF XML schema, this seems to be represented by the BitmapFormat enumeration which contains just PNG and JPG. (see https://github.com/BuildingSMART/BCF-XML/blob/master/Schemas/visinfo.xsd)

My proposal would be to represent the image formats using the extensions, instead of the ordinals in the API, or make it a string field in the XML and API so that a MIME type could be used e.g. "image/jpeg", as this would allow implementors to use a wider range of image formats. 

At very least the set of values should be consistent between the API and the XML.

**Comment by GeorgDangl** [comment]
Fixed by 0bc3e3d

We did agree to exclude BMP from the allowed formats since there's no real use case for it and it gets quite heavy on file size if someone were to send BMP. It's been still in the API spec because I forgot to remove it=)

I'm leaving this issue open if there's a need for more image formats.
